#!/bin/bash
#SBATCH -J LO_polymer_tr(C)
#SBATCH -o outputs/log # output and error file name (%j expands to jobID)
#SBATCH -e outputs/err
#SBATCH -N 1 # total number of nodes
#SBATCH -n 1 # total number of mpi tasks requested
#SBATCH -p icx # queue (partition) -- normal, development, etc.
#SBATCH -t 4:00:00 # run time (hh:mm:ss)
#SBATCH -A CTS24014 # Project number

#SBATCH --mail-user=rek@utexas.com
#SBATCH --mail-type=end     # email me when the job finishes

dns=code/bin/dns


shopt -s extglob
cd outputs
rm -r !("log"|"err")
cd ..
mkdir outputs/flowfield
mkdir outputs/particles

export OMP_NUM_THREADS=32
export OMP_STACKSIZE=2G
ulimit -s unlimited
$dns
