#!/bin/bash
#SBATCH -J my_job_name
#SBATCH -o outputs/log # output and error file name (%j expands to jobID)
#SBATCH -e outputs/err
#SBATCH -N 1 # total number of nodes
#SBATCH -n 1 # total number of mpi tasks requested
#SBATCH -p spr # queue (partition) -- normal, development, etc.
#SBATCH -t 2:00:00 # run time (hh:mm:ss)
#SBATCH -A CTS24014 # Project number

#SBATCH --mail-user=username@email.com
#SBATCH --mail-type=end     # email me when the job finishes

make polymer_dns

shopt -s extglob
cd outputs
rm -r !("log"|"err")
cd ..
mkdir outputs/flowfield
mkdir outputs/particles

export OMP_NUM_THREADS=100
export OMP_STACKSIZE=1G
ulimit -s unlimited

./code/bin/dns
