#!/bin/bash
#SBATCH -J [jobname here]
#SBATCH -o log # output and error file name (%j expands to jobID)
#SBATCH -e err
#SBATCH -N 2 # total number of nodes
#SBATCH -n 8 # total number of mpi tasks requested
#SBATCH -p spr # queue (partition) -- normal, development, etc.
#SBATCH -t 3:00:00 # run time (hh:mm:ss)
#SBATCH -A CTS24014 # Project number

#SBATCH --mail-user=[your email here]
#SBATCH --mail-type=end     # email me when the job finishes


rm -r outputs*

export OMP_NUM_THREADS=32
export OMP_STACKSIZE=1500M
ulimit -s unlimited

ibrun ./code/bin/dns
